services:
  laravel:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile.prod
      args:
        WWWGROUP: 'www-data'
    image: 'laravel_app_prod'
    container_name: php_discover
    environment:
      APP_ENV: production
      WWWUSER: 'www-data'
      LARAVEL_SAIL: 1
      XDEBUG_MODE: 'off'
    volumes:
      - .:/var/www/html
      - ./storage/framework/views:/var/www/html/storage/framework/views
      - ./bootstrap/cache:/var/www/html/bootstrap/cache
    networks:
      - discover
    command: "/usr/local/bin/docker-entrypoint.sh"

  mysql:
    image: mysql:8.0.32
    container_name: mysql_discover
    restart: always
    ports:
      - "3307:3306"
    environment:
        MYSQL_ROOT_PASSWORD: 'FullFist1007'
        MYSQL_DATABASE: 'discover'
        MYSQL_USER: 'discover'
        MYSQL_PASSWORD: 'FullFist1007'
    volumes:
        - 'mysql_data:/var/lib/mysql'
        - ./mysql/my.cnf:/etc/mysql/my.cnf
        - './docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql'
    networks:
        - discover
    healthcheck:
        test:
            - CMD
            - mysqladmin
            - ping
            - '-p${DB_PASSWORD}'
        retries: 3
        timeout: 5s

  nginx:
    image: nginx:alpine
    container_name: nginx_discover
    volumes:
      - .:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /home/debian/nginx/certs:/etc/nginx/certs:ro
    environment:
      - VIRTUAL_HOST=discover-playlist.ovh,www.discover-playlist.ovh
      - LETSENCRYPT_HOST=discover-playlist.ovh,www.discover-playlist.ovh
      - LETSENCRYPT_EMAIL=contact@robinberdier.com
    networks:
      - discover

volumes:
  mysql_data:
    driver: local

networks:
  discover:
    external: true
