# Utilisation de l'image Nginx officielle avec Alpine
FROM nginx:alpine

# Copier la configuration Nginx dans le conteneur
COPY docker/nginx/default.conf /etc/nginx/conf.d/default.conf

# Copier les fichiers de l'application (optionnel si des assets statiques sont nécessaires)
WORKDIR /var/www/html
COPY . /var/www/html

# Exposer le port 80 pour Nginx
EXPOSE 80

# Commande pour démarrer Nginx
CMD ["nginx", "-g", "daemon off;"]
